//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPodgotovka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emloyees
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public System.DateTime Birthday { get; set; }
        public int id_roles { get; set; }
        public bool IsActual { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
